[http]
    followredirects = true
    url = "URL/FUZZ"

[general]
    autocalibration = true
    colors = true
    rate = 100
    verbose = true

[input]
    wordlists = [
        "/home/thomas/Hacking/Tools/Wordlists/SecLists/Discovery/Web-Content/raft-small-directories.txt:FUZZ",
        "./urls_hosts_exemple.md:URL"
    ]

[output]
    outputfile = "./scans/ffuf/directories.json"
